# INFO
quarkus.application.name=MoneyStats

# Configurazione risorse statiche
quarkus.http.static-resources.index-page=index.html

# HTTP
quarkus.http.access-log.enabled=true
quarkus.http.record-request-start-time=true
quarkus.http.access-log.pattern=ip=%h user=%u method=%m requestUri="%U" responseCode=%s responseBytes=%b responseTime=%D
quarkus.http.access-log.exclude-pattern=/q/health/.*
quarkus.http.filter.index-nocache.matches=/*
quarkus.http.filter.index-nocache.header."Cache-Control"=no-cache
quarkus.http.auth.proactive=false
quarkus.http.proxy.proxy-address-forwarding=true

# FRONTEND
#quarkus.http.cors=true
quarkus.http.host=0.0.0.0
quarkus.http.cors.origins=http://localhost:8080
quarkus.http.cors.methods=GET,PUT,POST,DELETE,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with,x-device-id,cache-control,pragma

# DATABASE
quarkus.datasource.db-kind=oracle
quarkus.datasource.username=${oracle-moneystats-username}
quarkus.datasource.jdbc.url=${oracle-moneystats-url}
quarkus.datasource.password=${oracle-moneystats-password}

# HIBERNATE
quarkus.hibernate-orm.packages=carmine.pittella.home.model.entity
quarkus.hibernate-orm.dialect=org.hibernate.dialect.OracleDialect
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.physical-naming-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

# TOKEN JWT
mp.jwt.verify.issuer=carmine-home-app
mp.jwt.verify.publickey=${JWT_PUBLIC_KEY}
smallrye.jwt.sign.key=${JWT_PRIVATE_KEY}



