CREATE
OR REPLACE VIEW MNY.V_MOVIMENTI AS
SELECT m.TIPOLOGIA, m."DATA", m.TITOLO, m.IMPORTO, ca.CATEGORIA, h.HASHTAG, m.COMMENTO
FROM MNY.MOVIMENTO m
         JOIN MNY.CONTO c ON c.ID_CONTO = m.ID_CONTO
         JOIN MNY.CATEGORIA ca ON ca.ID_CATEGORIA = m.ID_CATEGORIA
         JOIN MNY.HASHTAG h ON h.ID_HASHTAG = m.ID_HASHTAG